### ISSUE TITLE
Why is every job link to Google.ca? 

### ISSUE THREAD

**Issue by RichardLitt** [izzydoesizzy/todevjobs#4]
That seems kind of counter-productive. :?

**Comment by izzydoesizzy** [comment]
Test data. None of it is real.

**Comment by izzydoesizzy** [comment]
Hi! I’ve signed up for a spam filtering service called BitBounce and I added you to my “whitelist”. That means you can email me and your emails will come through.

For people who aren’t on my whilelist, I’m charging $0.05 in Bitcoin for their email to get to my inbox. A cleaner inbox and more money? Win! You should check it out!

Sign up to get paid for emails here: https://bitbounce.io?ref=bitbounce

--

Unsubscribe from Iskender Piyale-Sheard's whitelist notification emails here: https://www.turing-cloud.com/unsubscribe_from_whitelist_email_notifications/3284795392
